# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17dbef691251721ed9837d9c3e71b5489e6aacfa7250654a2fdfcc29b905a93c0b11ec027649c9ce9451dbdb98245f8d89b5a408c89a3e4bd95cda740bb83499

test:
  secret_key_base: 17c49c447d1c0b447f8e03788d9daa519006ab80399702fdc9c5dfdb86425e0cc0f9f8c49c138da4b7d74f6517dd0814c8b2730538f4e8c02f271917f1d2f108

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
